export const TOGGLE_MENUBAR = "TOGGLE_MENUBAR";
export const FETCH_GALLERY = "FETCH_GALLERY";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_IMAGE = "FETCH_IMAGE";
export const SET_POSITION_ELEMENT = "SET_POSITION_ELEMENT";
export const RESET_POSITION_ELEMENT = "RESET_POSITION_ELEMENT";
export const HIDE_TO_UP = "HIDE_TO_UP";
export const DISPLAY_TO_UP = "DISPLAY_TO_UP";
